# Generated by Django 4.2.5 on 2024-03-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='creadted',
            new_name='created',
        ),
    ]
